AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  code-stats-aws-lambda

  Sample SAM Template for code-stats-aws-lambda

Globals:
  Function:
    Timeout: 10
    MemorySize: 128

    Tracing: Active
  Api:
    TracingEnabled: true
Resources:
  GetSummaryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/get-summary/
      Handler: index.handler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      MemorySize: 256
      Events:
        GetSummary:
          Type: Api
          Properties:
            Path: /get-summary
            Method: get
            Auth:
              Authorizer: AWS_IAM
      Environment:
        Variables:
          SECRET_ARN: arn:aws:secretsmanager:eu-west-2:885135949562:secret:wakatime-api-key-X9oF3v
          NODE_ENV: production
          API_KEY:
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        EntryPoints:
          - index.ts

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: "true"
Outputs:
  GetSummaryApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  GetSummaryFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt GetSummaryFunction.Arn
  GetSummaryFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt GetSummaryFunctionRole.Arn
